import type { PrimitiveType, SdfNode } from "../types";
import { BOOLEANS, PRIMITIVES, TRANSFORMS } from "./registry";

type EmitCtx = {
  pointCounter: number;
  distCounter: number;
  matCounter: number;
  stmts: string[];
  primitiveHelpers: Set<PrimitiveType>;
  extraHelpers: Map<string, string>;
};

type WalkResult = { dist: string; mat: string };

function nextPoint(ctx: EmitCtx): string {
  return `p${++ctx.pointCounter}`;
}
function nextDist(ctx: EmitCtx): string {
  return `d${++ctx.distCounter}`;
}
function nextMat(ctx: EmitCtx): string {
  return `m${++ctx.matCounter}`;
}

function walk(node: SdfNode, currentPoint: string, ctx: EmitCtx): WalkResult {
  if (!node.enabled) {
    const d = nextDist(ctx);
    const m = nextMat(ctx);
    ctx.stmts.push(`float ${d} = 1e6; // disabled: ${node.type}`);
    ctx.stmts.push(`int ${m} = 0;`);
    return { dist: d, mat: m };
  }

  if (node.kind === "primitive") {
    const def = PRIMITIVES[node.type];
    ctx.primitiveHelpers.add(node.type);
    const d = nextDist(ctx);
    const m = nextMat(ctx);
    const matId = Math.max(0, Math.round(node.matId ?? 0));
    ctx.stmts.push(`float ${d} = ${def.call(currentPoint, node.params)};`);
    ctx.stmts.push(`int ${m} = ${matId};`);
    return { dist: d, mat: m };
  }

  if (node.kind === "transform") {
    const def = TRANSFORMS[node.type];
    if (def.helpers) {
      for (const h of def.helpers) ctx.extraHelpers.set(h.name, h.code);
    }
    let childPoint = currentPoint;
    if (def.emitPoint) {
      const np = nextPoint(ctx);
      for (const stmt of def.emitPoint(np, currentPoint, node.params)) {
        ctx.stmts.push(stmt);
      }
      childPoint = np;
    }
    if (!node.child) {
      const d = nextDist(ctx);
      const m = nextMat(ctx);
      ctx.stmts.push(`float ${d} = 1e6; // transform without child`);
      ctx.stmts.push(`int ${m} = 0;`);
      return { dist: d, mat: m };
    }
    const child = walk(node.child, childPoint, ctx);
    if (def.emitDistance) {
      const nd = nextDist(ctx);
      for (const stmt of def.emitDistance(nd, child.dist, childPoint, node.params)) {
        ctx.stmts.push(stmt);
      }
      return { dist: nd, mat: child.mat };
    }
    return child;
  }

  // boolean
  const def = BOOLEANS[node.type];
  if (def.helpers) {
    for (const h of def.helpers) ctx.extraHelpers.set(h.name, h.code);
  }
  const active = node.children.filter((c) => c.enabled);
  if (active.length === 0) {
    const d = nextDist(ctx);
    const m = nextMat(ctx);
    ctx.stmts.push(`float ${d} = 1e6; // empty ${node.type}`);
    ctx.stmts.push(`int ${m} = 0;`);
    return { dist: d, mat: m };
  }
  const childResults = active.map((c) => walk(c, currentPoint, ctx));
  if (childResults.length === 1) return childResults[0];

  let acc = childResults[0];
  for (let i = 1; i < childResults.length; i++) {
    const b = childResults[i];
    const nd = nextDist(ctx);
    const nm = nextMat(ctx);
    const stmts = def.pairwise(acc, b, node.params, nd, nm);
    for (const s of stmts) ctx.stmts.push(s);
    acc = { dist: nd, mat: nm };
  }
  return acc;
}

export type ShaderParts = {
  helpers: string[];
  bodyStmts: string[];
  finalDist: string;
  finalMat: string;
};

/** Dialect-agnostic shader pieces. Tracks both distance and material id. */
export function buildParts(root: SdfNode | null): ShaderParts | null {
  if (!root) return null;
  const ctx: EmitCtx = {
    pointCounter: 0,
    distCounter: 0,
    matCounter: 0,
    stmts: [],
    primitiveHelpers: new Set(),
    extraHelpers: new Map(),
  };
  ctx.stmts.push(`vector p0 = P - Center;`);
  const final = walk(root, "p0", ctx);
  const helpers = [
    ...[...ctx.primitiveHelpers].sort().map((t) => PRIMITIVES[t].helperCode),
    ...ctx.extraHelpers.values(),
  ];
  return {
    helpers,
    bodyStmts: ctx.stmts,
    finalDist: final.dist,
    finalMat: final.mat,
  };
}

export type EmitResult = {
  code: string;
  empty: boolean;
};

const HEADER = `// Generated by Vectron Formula Generator
#include "octane-oslintrin.h"
`;

export function emitOSL(root: SdfNode | null): EmitResult {
  if (!root) {
    return {
      empty: true,
      code: `${HEADER}
shader vectron(
    vector Center = 0,
    output _sdf out = _SDFDEF)
{
    // Add a primitive from the Library panel to get started.
    out.dist = 1e6;
}
`,
    };
  }

  const parts = buildParts(root)!;
  const helpersText = parts.helpers.length
    ? parts.helpers.join("\n\n") + "\n"
    : "";
  const indent = (s: string) =>
    s.split("\n").map((l) => (l ? "    " + l : l)).join("\n");
  const body = parts.bodyStmts.map((s) => indent(s)).join("\n");

  const code = `${HEADER}
${helpersText}
shader vectron(
    vector Center = 0,
    output _sdf out = _SDFDEF)
{
${body}
    out.dist = ${parts.finalDist};
    out.matId = ${parts.finalMat};
}
`;

  return { code, empty: false };
}
