import type { PrimitiveType, SdfNode } from "../types";
import { BOOLEANS, PRIMITIVES, TRANSFORMS } from "./registry";

type EmitCtx = {
  pointCounter: number;
  distCounter: number;
  stmts: string[];
  primitiveHelpers: Set<PrimitiveType>;
  extraHelpers: Map<string, string>;
};

function nextPoint(ctx: EmitCtx): string {
  return `p${++ctx.pointCounter}`;
}
function nextDist(ctx: EmitCtx): string {
  return `d${++ctx.distCounter}`;
}

function walk(node: SdfNode, currentPoint: string, ctx: EmitCtx): string {
  if (!node.enabled) {
    const dv = nextDist(ctx);
    ctx.stmts.push(`float ${dv} = 1e6; // disabled: ${node.type}`);
    return dv;
  }

  if (node.kind === "primitive") {
    const def = PRIMITIVES[node.type];
    ctx.primitiveHelpers.add(node.type);
    const dv = nextDist(ctx);
    ctx.stmts.push(`float ${dv} = ${def.call(currentPoint, node.params)};`);
    return dv;
  }

  if (node.kind === "transform") {
    const def = TRANSFORMS[node.type];
    if (def.helpers) {
      for (const h of def.helpers) ctx.extraHelpers.set(h.name, h.code);
    }
    let childPoint = currentPoint;
    if (def.emitPoint) {
      const np = nextPoint(ctx);
      for (const stmt of def.emitPoint(np, currentPoint, node.params)) {
        ctx.stmts.push(stmt);
      }
      childPoint = np;
    }
    if (!node.child) {
      const dv = nextDist(ctx);
      ctx.stmts.push(`float ${dv} = 1e6; // transform without child`);
      return dv;
    }
    const childDist = walk(node.child, childPoint, ctx);
    if (def.emitDistance) {
      const nd = nextDist(ctx);
      for (const stmt of def.emitDistance(nd, childDist, childPoint, node.params)) {
        ctx.stmts.push(stmt);
      }
      return nd;
    }
    return childDist;
  }

  // boolean
  const def = BOOLEANS[node.type];
  if (def.helpers) {
    for (const h of def.helpers) ctx.extraHelpers.set(h.name, h.code);
  }
  const activeChildren = node.children.filter((c) => c.enabled);
  if (activeChildren.length === 0) {
    const dv = nextDist(ctx);
    ctx.stmts.push(`float ${dv} = 1e6; // empty ${node.type}`);
    return dv;
  }
  const childDists = activeChildren.map((c) => walk(c, currentPoint, ctx));
  if (childDists.length === 1) return childDists[0];
  const dv = nextDist(ctx);
  ctx.stmts.push(`float ${dv} = ${def.combine(childDists, node.params)};`);
  return dv;
}

export type ShaderParts = {
  helpers: string[];
  bodyStmts: string[];
  finalDist: string;
};

/** Build dialect-agnostic shader pieces. The output uses OSL types (`vector`),
 *  but is structured so that a simple text transform can yield GLSL. */
export function buildParts(root: SdfNode | null): ShaderParts | null {
  if (!root) return null;
  const ctx: EmitCtx = {
    pointCounter: 0,
    distCounter: 0,
    stmts: [],
    primitiveHelpers: new Set(),
    extraHelpers: new Map(),
  };
  ctx.stmts.push(`vector p0 = P - Center;`);
  const finalDist = walk(root, "p0", ctx);
  const helpers = [
    ...[...ctx.primitiveHelpers].sort().map((t) => PRIMITIVES[t].helperCode),
    ...ctx.extraHelpers.values(),
  ];
  return { helpers, bodyStmts: ctx.stmts, finalDist };
}

export type EmitResult = {
  code: string;
  empty: boolean;
};

const HEADER = `// Generated by Vectron Formula Generator
#include "octane-oslintrin.h"
`;

export function emitOSL(root: SdfNode | null): EmitResult {
  if (!root) {
    return {
      empty: true,
      code: `${HEADER}
shader vectron(
    vector Center = 0,
    output _sdf out = _SDFDEF)
{
    // Add a primitive from the Library panel to get started.
    out.dist = 1e6;
}
`,
    };
  }

  const parts = buildParts(root)!;
  const helpersText = parts.helpers.length
    ? parts.helpers.join("\n\n") + "\n"
    : "";
  const indent = (s: string) => s.split("\n").map((l) => (l ? "    " + l : l)).join("\n");
  const body = parts.bodyStmts.map((s) => indent(s)).join("\n");

  const code = `${HEADER}
${helpersText}
shader vectron(
    vector Center = 0,
    output _sdf out = _SDFDEF)
{
${body}
    out.dist = ${parts.finalDist};
}
`;

  return { code, empty: false };
}
